version: '3'
services:
  nginx:
    image: nginx
    restart: always
    # network_mode: "host"
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d